### ISSUE TITLE
[BUG] Workspaces collapses into a dot after locking screen/going inactive

### ISSUE THREAD

**Issue by HazemSayad** [pop-os/cosmic-workspaces#43] opened 2022-01-28 22:18 UTC
![Screenshot from 2022-01-24 18-57-37](https://user-images.githubusercontent.com/94578938/151629059-c5e297fd-2abc-444d-8cc6-dbcd5e25e224.png)

Only after the screen goes inactive or the screen is locked, the workspace collapses to a dot. I was able to reproduce it constantly after locking my screen (Super+Esc) or setting the blank screen to 1 min

**Comment by 13r0ck** [comment] 2022-02-01 02:32
Can you please provide more information about your configuration?
It seems like you have quite a few extensions enabled, does the bug still persist even if you disable all other extensions?

**Comment by ghost** [comment] 2022-02-02 07:49
It's the same issue #35 #32. The yellow dot is the border colour of the active workspace , as there's no workspace view on screen due to the bug it just collapsed into a dot.

**Comment by HazemSayad** [comment] 2022-02-02 13:19
> does the bug still persist even if you disable all other extensions?

@13r0ck Yes, I made sure to isolate the reason and it was workspaces extension. But if it is of any importance, i did an upgrade from 21.04 to 21.10 instead of a fresh install. I discussed with reddit before submitting this issue and i found that many complain from the same issue. If i can assist you more, please do tell

**Comment by 13r0ck** [comment] 2022-02-02 17:46
Please provide me with the version both of you are using
`apt policy gnome-shell-extension-cosmic-workspaces`



I am unable to reproduce the bug on a clean install of Pop!_OS.

My attempt:
1. Put dock on right
2. Open workspaces view (`Suoer` + `d`)
3. suspend machine (tried both suspend and lock)
After suspend I am still seeing the same sized workspaces picker

@HazemSayad & @olfREG314 Please provide me with the correct steps to reproduce

**Comment by HazemSayad** [comment] 2022-02-02 18:14
@13r0ck 
```
hazem@pop-os:~$ apt policy gnome-shell-extension-cosmic-workspaces
gnome-shell-extension-cosmic-workspaces:
  Installed: 0.1.0~1643679642~21.10~fb53648
  Candidate: 0.1.0~1643679642~21.10~fb53648
  Version table:
 *** 0.1.0~1643679642~21.10~fb53648 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status
```
My steps to reproduce it consistently:
1. Restart `cosmic-workspaces` extension just to start clean and a working workspaces (since usually mine goes into dot mode)
2. Test to make sure all looks good; view the workspaces with `Super+D` (works good)
3. Changing the state of the screen from sleep to awake seems to trigger it, so on my end i can trigger it using: 
  a. `Super+Esc` to lock screen even if the screen doesn't sleep (the screen sleeps not the PC aka dark/turnoff)
  b. Setting the "Blank Screen" timer to `1 min` while "Dim Screen When Inactive" is on in `Settings > Power > Power Saving`
  c. Closing the laptop screen lid and PC going to sleep, then re-opening the screen > enter my password 
4. After step 3 you check with Super+D and it is a dot

I am not on a clean install for Pop OS 21.10, I upgraded from 21.04 using System76 guide through the terminal, it was flawless during the upgrade and a smooth ride, nothing complained of anything.

I don't know about others who are facing this issue if they also upgraded from `21.04` to `21.10`. Maybe try that.

I haven't tried uninstalling the `cosmic-workspaces` extension yet; I only tried turning it off and on again to fix this issue. Do you recommend uninstalling it and reinstalling it?

**Comment by 13r0ck** [comment] 2022-02-02 18:27
Thank you! I'm still not seeing the bug unfortunately

Are you connected to any external displays?
What is your laptop's resolution?
Do you have any scaling settings applied?
Have you changed any values for cosmic workspaces in your dconf-setttings?
Can you link me the reddit discussion? I would like to see if anything someone else has said can help me reproduce it

**Comment by HazemSayad** [comment] 2022-02-02 18:45
> Thank you! I'm still not seeing the bug unfortunately

Did you try a 21.04 to 21.10 upgrade?

> Are you connected to any external displays?

Non, just the laptop's display

>  Do you have any scaling settings applied?

>  What is your laptop's resolution?

![image](https://user-images.githubusercontent.com/94578938/152216866-a2dc6fb2-f050-4ce6-b5b1-a039a13d8477.png)

>  Have you changed any values for cosmic workspaces in your dconf-setttings?

Non, never touched it

>  Can you link me the reddit discussion? I would like to see if anything someone else has said can help me reproduce it

Useless, but [here it is](https://www.reddit.com/r/pop_os/comments/sbpove/bug_workspaces_applications_preview_gets_hidden/) 


Though this only started happening right after the upgrade from 21.04 and [this is the guide i followed from System76](https://support.system76.com/articles/upgrade-pop/#terminal-upgrade)

**Comment by 13r0ck** [comment] 2022-02-02 23:00
I was able to reproduce the bug. I can confirm it will be fixed after #45 is released.

The steps to reproduce.
1. Disable cosmic-dock
2. Enable floating-dock

**Comment by HazemSayad** [comment] 2022-02-02 23:08
nice catch, how is the dock connected to the worspaces extension btw? tho in my testing, i didn't turn on any dock, neither the cosmic nor floating and i confirmed it was workspaces related instead of some other 3rd party extension. again, nice catch! and thanks to the whole team from system76 <3

**Comment by 13r0ck** [comment] 2022-02-03 03:24
> how is the dock connected to the worspaces extension btw?

Gnome extensions have an API to interact with eachother. [This](https://github.com/pop-os/cosmic-workspaces/blob/master_impish/util.js#L65) is the function cosmic-workspaces uses to get the dock object, which we can then read/write any data from there we like.

> i didn't turn on any dock, neither the cosmic nor floating and i confirmed it was workspaces related instead of some other 3rd party extension

Hmm, interesting that you were able to get it without another extension. Either way, something is setting he workspaces picker's height to a negative value. Fixing wherever that is should solve the issue in both situations :crossed_fingers: 

> thanks to the whole team from system76 <3

Thank you! I will let them know!

**Comment by ghost** [comment] 2022-02-03 09:54
> Please provide me with the version both of you are using `apt policy gnome-shell-extension-cosmic-workspaces`
> 
> I am unable to reproduce the bug on a clean install of Pop!_OS.
> 
> My attempt:
> 
>     1. Put dock on right
> 
>     2. Open workspaces view (`Suoer` + `d`)
> 
>     3. suspend machine (tried both suspend and lock)
>        After suspend I am still seeing the same sized workspaces picker
> 
> 
> @HazemSayad & @olfREG314 Please provide me with the correct steps to reproduce

gnome-shell-extension-cosmic-workspaces:
  Installed: 0.1.0~1643679642~21.10~fb53648
  Candidate: 0.1.0~1643679642~21.10~fb53648
  Version table:
 *** 0.1.0~1643679642~21.10~fb53648 1001
       1001 http://apt.pop-os.org/release impish/main amd64 Packages
       1001 http://apt.pop-os.org/release impish/main i386 Packages
        100 /var/lib/dpkg/status


Hey, I tried with cosmic-dock everything is working fine there but when using dash to dock I have to restart the gnome shell to get the workspace view after every suspend and every time I connect to external display the problem reoccur. The same log error that I had posted on #32. Looks the problem occur because of dash-to-dock
I just disable & enable the workspace with the shortcut. Works for now.

Reproduce-
-install dash to dock
-disable `gnome-extensions disable cosmic-dock@system76.com
-restart the gnome environment
-suspend the laptop
-open workspace & there's the yellow dot

As you said #41, may be this is the problem
```
In a rare "race-like" condition that only occurs on some hardware, cosmic-dock can be loaded before the monitor is ready to display, thus cosmic-dock runs in a "headless" mode, and mainDock returns null. Because cosmic-workspaces is loaded after cosmic-dock, this causes the dock to be functional, but the rest of the UI to not be.
```
its merged but I don't know the update is pushed or not.

**Comment by 13r0ck** [comment] 2022-04-11 21:29
Reason for closing in related issue here: https://github.com/pop-os/cosmic-workspaces/issues/35#issuecomment-1095584310

**Closed as completed by 13r0ck** 2022-04-11 21:29 UTC
Labels: bug, confirmed
