### ISSUE TITLE
[Feature Request] Toggle Workspace: Horizontal or Vertical

### ISSUE THREAD

**Issue by postnick** [pop-os/cosmic-workspaces#58] opened 2022-03-31 23:13 UTC
Some users prefer horizontal, some users prefer vertical workspace and corresponding gestures. I know people are passionate one way or another. 

I propose an option on the gnome settings > Desktop > Workspace tab to allow the user to decide the direction they like to go. I'm very used to pure GNOME gestures and they seem right to me.  Gesturing up should pull up applications to me, so having the ability to pick would add a whole level of customization for users! 

Thank you for the consideration.

**Comment by 13r0ck** [comment] 2022-04-05 02:59
Pop!_OS comes pre-installed with gnome-extensions. You can disable the cosmic-workspaces extension there :smile:

**Comment by jacobgkau** [comment] 2022-04-05 16:41
It's worth noting that making this configurable is on the roadmap for COSMIC, it's just not something currently implemented.

I am closing this feature request as a duplicate of https://github.com/pop-os/cosmic/issues/30, thank you for the report.

**Closed as completed by jacobgkau** 2022-04-05 16:41 UTC
