### ISSUE TITLE
Horizontal workspace view

### ISSUE THREAD

**Issue by deverebor** [pop-os/cosmic-workspaces#77] opened 2022-07-02 20:52 UTC
It would be interesting for the desktop choice menu to be horizontal and not vertical. This proposes a significant improvement in productivity. Just like it is in the default gnome.

![image](https://user-images.githubusercontent.com/62480586/177015897-5688a0ef-a895-4ce8-beba-acbb68fce69b.png)

I believe it would be an interesting feature to choose between vertical and horizontal. Since in the near future it will no longer be possible to disable the workspaces extension and use the gnome default. Having that option would be quite interesting.

**Comment by leviport** [comment] 2022-07-05 13:15
Duplicate of https://github.com/pop-os/cosmic/issues/30

**Closed as completed by leviport** 2022-07-05 13:15 UTC
