### ISSUE TITLE
22.04: Workspaces menu stops showing display thumbnails after changing dock position

### ISSUE THREAD

**Issue by jacobgkau** [pop-os/cosmic-workspaces#57] opened 2022-03-30 22:48 UTC
...until GNOME Shell is restarted.

Not sure if it's similar to https://github.com/pop-os/cosmic-workspaces/issues/44 in cause, but the symptom is kind of different/opposite, and this one's new with 22.04.

**Comment by 13r0ck** [comment] 2022-03-31 02:32
Duplicate of pop-os/cosmic-dock#129

**Closed as completed by 13r0ck** 2022-03-31 02:32 UTC
